In [2]:
import numpy as np

In [3]:
Z = np.zeros(10)

In [4]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
Z1 = np.zeros((10,10))

In [7]:
Z1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
O = np.ones((10,10))

In [9]:
O

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
R = np.random.random((10,10))

In [11]:
R

array([[0.07593482, 0.34521451, 0.16841727, 0.82355046, 0.97542435,
        0.5442893 , 0.69252148, 0.81469935, 0.20772367, 0.27388825],
       [0.64049944, 0.11766103, 0.19906376, 0.92249242, 0.74390001,
        0.19920257, 0.28846043, 0.96868983, 0.34107828, 0.72263563],
       [0.3436097 , 0.46715413, 0.66536   , 0.13831858, 0.51199781,
        0.7590753 , 0.366832  , 0.42208839, 0.58417702, 0.13099763],
       [0.54606334, 0.72561333, 0.80073173, 0.39981181, 0.60665564,
        0.12651843, 0.44357043, 0.19606326, 0.84031523, 0.00211232],
       [0.82265343, 0.27037879, 0.0851556 , 0.32545706, 0.82451113,
        0.6822037 , 0.5528251 , 0.87307857, 0.24489875, 0.53079295],
       [0.32940394, 0.62240184, 0.45018466, 0.92664145, 0.8061175 ,
        0.94828161, 0.84079209, 0.49824696, 0.21295163, 0.84619666],
       [0.8819751 , 0.61859743, 0.21882383, 0.10996601, 0.56269987,
        0.82401984, 0.03980076, 0.14281129, 0.79629899, 0.8985114 ],
       [0.94626079, 0.24307021, 0.8845854

In [13]:
G = np.random.randn(10,10)

In [14]:
G

array([[ 1.65241887,  0.07424908, -0.06099936, -0.26165787, -0.78185972,
        -2.17394083,  1.28248352, -0.86056415, -1.00414463, -2.55648568],
       [-1.18123358,  1.20138206,  1.61142724,  0.17942796, -0.53493045,
        -1.91093521,  0.48525652, -1.12496673,  1.46966785, -0.06920858],
       [-1.11885038,  0.44382878, -0.29608632,  1.12560051, -0.54552071,
         1.01965303,  0.32640464, -0.88387673, -0.52260318,  1.73477821],
       [-0.35519381, -0.52390876, -0.11635815, -0.04863421, -2.23616404,
         0.92909083, -0.15597536,  1.03824958,  0.06616592, -0.5806972 ],
       [-0.84867566,  0.12620796,  0.26954655,  0.10298693,  1.06051488,
         0.45771321,  0.15580307,  1.17050305, -0.66451057,  1.11608611],
       [-0.36825506, -1.83454089,  0.84849438, -1.65733236,  0.49679251,
         0.24101901,  1.8918763 , -0.94906173, -1.01739351, -0.83985501],
       [-0.74505073,  2.24647126,  2.44155849, -2.73404921,  0.06105826,
        -0.41878553, -1.31341461, -0.28850407

In [15]:
G.mean()

-0.04970310199579618

In [16]:
G.var()

1.0746830668484217